# Generated by Django 4.1.7 on 2023-04-01 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this listing', max_length=512)),
                ('url', models.CharField(help_text='The website URL you want to crawl', max_length=512)),
                ('selector', models.CharField(help_text='The specific CSS selector for the element you want to watch', max_length=512)),
                ('period', models.IntegerField(choices=[(1, 'One Min'), (10, 'Ten Min'), (20, 'Twenty Min'), (60, 'One Hour')], help_text='The time period to check the website')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this listing is actively being checked or not')),
                ('content_hash', models.IntegerField(blank=True, help_text='The hash of the latest website content that has been checked', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The creation date of this listing')),
                ('scheduler', models.OneToOneField(blank=True, help_text='The scheduler for this listing', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
                ('user', models.OneToOneField(help_text='The user that created this listing', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
