# Generated by Django 4.1.7 on 2023-04-01 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this listing is actively being checked or not'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='scheduler',
            field=models.OneToOneField(blank=True, editable=False, help_text='The scheduler for this listing', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
