# Generated by Django 4.1.7 on 2023-04-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_listing_is_active_alter_listing_scheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='content_hash',
            field=models.IntegerField(blank=True, editable=False, help_text='The hash of the latest website content that has been checked', null=True),
        ),
    ]
