# Generated by Django 4.1.7 on 2023-04-01 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('listing', '0004_alter_listing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='content_hash',
            field=models.IntegerField(blank=True, help_text='The hash of the latest website content that has been checked', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='scheduler',
            field=models.OneToOneField(blank=True, help_text='The scheduler for this listing', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
