# Generated by Django 4.1.7 on 2023-04-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_alter_listing_content_hash_alter_listing_scheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='content',
            field=models.TextField(blank=True, help_text='The latest website content that has been checked', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='content_hash',
            field=models.IntegerField(blank=True, help_text='The hash of the latest website content that has been checked', null=True),
        ),
    ]
