# Generated by Django 4.1.7 on 2023-04-02 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_listing_content_alter_listing_content_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='url',
            new_name='crawl_url',
        ),
    ]
